data:
  train_path: "data/train/train_data.csv"
  inference_path: "test"

train:
  model: 
    logistic_regression:
      type: logistic_regression
      params: 
        max_iter: 3000  
    decision_tree:
      type: decision_tree
      params: 
        max_depth: 5
    random_forest:
      type: random_forest
      params: 
        max_depth: 5
  stratify: True
  n_cv: 5
  random_seed: 42
  target_col: "Loan_Status"
  true_value: "Y"
  drop_features: ["Loan_ID"]
  selection_metrics: "roc_auc"

inference:
  metadata_path: "test"
  allow_missing_features: True
  inference_report_path: "test"

artifact:
  save_dir: "data/artifacts"
  metadata_name: "test"
  only_best: False